# Generated by Django 5.2.1 on 2025-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleApp', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined_team',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
