# Generated by Django 5.2.1 on 2025-05-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleApp', '0003_alter_member_date_joined_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='access_level',
        ),
    ]
